#! /bin/sh

sxhkd &

picom --experimental-backends &

$HOME/.config/polybar/launch.sh

nitrogen --restore

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 0
xrandr --output eDP-1 --scale 0.5x0.5

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
