[character]      # The name of the module we are configuring is "character"
symbol = "➜"     # The "symbol" segment is being set to "➜"

[conda]
disabled = true

[git_status]
conflicted_count.enabled = true
untracked_count.enabled = true
stashed_count.enabled = true
modified_count.enabled = true
staged_count.enabled = true
modified_count.enabled = true
deleted_count.enabled = true
